/* ═══════════════════════════════════════════════════════════════
   fetch-fonts — bring the two typefaces in-house

     node tools/fetch-fonts.js

   PLAN §11 wants the Google Fonts link gone: it is a third party on
   the critical path of every page load, it tells them who is reading
   the wall, and it is the only reason the Content-Security-Policy
   has to name a host it does not control.

   This downloads the woff2 files Google serves for Press Start 2P
   and Figtree, writes assets/fonts/fonts.css beside them, and
   rewrites the <link> in index.html. http.js notices assets/fonts/
   exists at boot and tightens style-src and font-src to 'self'
   automatically, so there is nothing else to change.

   Run once, commit the result. It is deliberately a command rather
   than something the build does: it reaches the network, and a build
   step that quietly downloads files is a build step nobody audits.

   Both faces are Open Font License; the licence text comes down with
   them into assets/fonts/OFL.txt.
   ═══════════════════════════════════════════════════════════════ */
'use strict';

const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const OUT = path.join(ROOT, 'assets', 'fonts');

/* The CSS endpoint serves different files per user-agent; asking as a
   modern browser gets woff2, which is the only format worth shipping. */
const UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 ' +
  '(KHTML, like Gecko) Chrome/124.0 Safari/537.36';
const CSS_URL = 'https://fonts.googleapis.com/css2' +
  '?family=Press+Start+2P&family=Figtree:wght@300;400;500;600;700&display=swap';

const OFL = 'https://raw.githubusercontent.com/googlefonts/' +
  'PressStart2P/main/OFL.txt';

async function get(url, as = 'text') {
  const res = await fetch(url, { headers: { 'user-agent': UA } });
  if (!res.ok) throw new Error(`${url} → ${res.status}`);
  return as === 'text' ? res.text() : Buffer.from(await res.arrayBuffer());
}

(async () => {
  fs.mkdirSync(OUT, { recursive: true });
  console.log('\n  fetching the stylesheet…');
  let css = await get(CSS_URL);

  /* Every src: url(...) in the returned CSS, pulled down and repointed at
     the local copy. The name comes from the URL's own last segment, which
     Google keeps stable and unique per face+subset. */
  const urls = [...new Set(css.match(/https:\/\/fonts\.gstatic\.com\/[^)]+/g) || [])];
  if (!urls.length) throw new Error('no font files in that stylesheet');

  let bytes = 0;
  for (const url of urls) {
    const name = url.split('/').pop().split('?')[0];
    const buf = await get(url, 'buffer');
    fs.writeFileSync(path.join(OUT, name), buf);
    css = css.split(url).join(`./${name}`);
    bytes += buf.length;
    console.log(`  ${name.padEnd(42)} ${(buf.length / 1024).toFixed(1)} KB`);
  }

  fs.writeFileSync(path.join(OUT, 'fonts.css'),
    `/* Generated by tools/fetch-fonts.js — do not edit.\n` +
    `   Press Start 2P and Figtree, SIL Open Font License (see OFL.txt). */\n\n${css}`);

  try {
    fs.writeFileSync(path.join(OUT, 'OFL.txt'), await get(OFL));
  } catch (err) {
    console.warn(`  (could not fetch the licence text — ${err.message})`);
  }

  /* …and take Google out of the page */
  const indexFile = path.join(ROOT, 'index.html');
  const before = fs.readFileSync(indexFile, 'utf8');
  const after = before.replace(
    /[ \t]*<link rel="preconnect"[^>]*>\n|[ \t]*<link href="https:\/\/fonts\.googleapis\.com[^>]*>\n/g,
    '')
    .replace(/([ \t]*)<link rel="stylesheet" href="styles\.css">/,
      '$1<link rel="stylesheet" href="assets/fonts/fonts.css">\n$1<link rel="stylesheet" href="styles.css">');

  if (after !== before) {
    fs.writeFileSync(indexFile, after);
    console.log('\n  index.html now loads the local copies.');
  } else {
    console.log('\n  index.html already points at the local copies.');
  }

  console.log(`\n  ${urls.length} file(s), ${(bytes / 1024).toFixed(1)} KB total.`);
  console.log('  Restart the server: it tightens the CSP when assets/fonts/ exists.\n');
})().catch(err => {
  console.error(`\n  failed: ${err.message}\n`);
  process.exit(1);
});
