/* ═══════════════════════════════════════════════════════════════
   make-env — the production environment file, without hand-typing

     node tools/make-env.js [outfile]      default: ./.env
     node tools/make-env.js --check [file] what is still missing

   RUNBOOK step 3 says "generate the secrets, do not invent them",
   which is the sort of instruction everybody agrees with and somebody
   eventually ignores at 1am. So this does it: reads .env.example,
   fills every value that can be generated with 32 bytes of
   crypto.randomBytes, sets the handful that production always wants
   the same way, and leaves a loud TODO on the ones that can only come
   from somewhere else.

   Refuses to overwrite. Rotating SESSION_SECRET silently would log
   out every guest on the wall and take their history with it — that
   has to be a deliberate act, not a re-run.

   The output is gitignored (.env and .env.* both are). On the box it
   belongs at /etc/s37.env, chmod 600, owned by root.
   ═══════════════════════════════════════════════════════════════ */
'use strict';

const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

const ROOT = path.join(__dirname, '..');
const secret = () => crypto.randomBytes(32).toString('base64url');

/* What production always wants. These are not secrets, they are the
   difference between a dev box and a real one, and getting any of them
   wrong is a bad afternoon rather than a wrong answer. */
const PROD = {
  NODE_ENV: 'production',
  PORT: '5174',
  /* Caddy terminates TLS and replaces any inbound X-Forwarded-For, so the
     forwarded address is the real one. Left at 0 the entire internet shares
     one IP and every per-IP cap applies to all of it at once. */
  TRUST_PROXY: '1',
  /* the cookie is worthless over plain http, and there is no plain http */
  COOKIE_SECURE: '1',
  DATA_DIR: '/srv/s37/data',
  STATE_DIR: '/srv/s37',
  TG_MODE: 'webhook'
};

/* Generated here, once, and never regenerated by a re-run. */
const GENERATE = ['SESSION_SECRET', 'TG_WEBHOOK_SECRET'];

/* Can only come from somewhere else — a person, a bot, a dashboard. */
const FROM_ELSEWHERE = {
  TG_BOT_TOKEN: 'BotFather → /newbot',
  TG_CHAT_ID: 'npm run tg -- --chat, after adding the bot to the group',
  TG_MOD_IDS: 'the same command lists everyone who has spoken to the bot',
  PUBLIC_URL: 'https://project-s37.com — no trailing slash',
  INSTAPAY_URL: 'the ipn.eg link you already have',
  INSTAPAY_HANDLE: 'mohaby@instapay',
  LITESTREAM_ACCESS_KEY_ID: 'Cloudflare → R2 → Manage API tokens',
  LITESTREAM_SECRET_ACCESS_KEY: 'shown once, when the token is created',
  R2_BUCKET: 'the bucket name you made',
  R2_ENDPOINT: 'https://<accountid>.r2.cloudflarestorage.com'
};

const TODO = '__FILL_ME_IN__';

/* ── ─────────────────────────────────────────────────────────── */

/* Walks .env.example rather than writing a file from scratch, so every
   comment explaining what a variable is for comes along with it — and a
   variable added to the template later cannot be silently missed here. */
function build() {
  const template = fs.readFileSync(path.join(ROOT, '.env.example'), 'utf8');
  const seen = new Set();

  const out = template.split(/\r?\n/).map(line => {
    const m = line.match(/^([A-Z][A-Z0-9_]*)=(.*)$/);
    if (!m) return line;
    const [, key, existing] = m;
    seen.add(key);

    if (GENERATE.includes(key)) return `${key}=${secret()}`;
    if (Object.prototype.hasOwnProperty.call(PROD, key)) return `${key}=${PROD[key]}`;
    if (Object.prototype.hasOwnProperty.call(FROM_ELSEWHERE, key)) {
      /* keep whatever the template already suggested if it looks real */
      const keep = existing && !existing.startsWith('<') ? existing : '';
      if (keep) return `${key}=${keep}`;
      /* The hint goes on its own line, never after the value. systemd's
         EnvironmentFile only treats a line *starting* with # as a comment,
         so `KEY=  # hint` would set KEY to "  # hint" — and the boot's
         fail-fast, which checks for an empty value, would wave it through
         and then hand the Telegram API a bot token made of English. */
      return `# TODO — ${FROM_ELSEWHERE[key]}\n${key}=`;
    }
    return line;
  }).join('\n');

  const missed = Object.keys(FROM_ELSEWHERE).filter(k => !seen.has(k));
  if (missed.length) throw new Error(`.env.example has no line for ${missed.join(', ')}`);
  return out;
}

function check(file) {
  if (!fs.existsSync(file)) { console.error(`\n  no ${file} yet — run without --check first\n`); process.exit(1); }
  /* envfile.js has the systemd parsing rules — notably that a value is
     everything after the '=', because a hash is a legal character in a
     secret and systemd does no trailing-comment stripping. */
  const vars = require('./envfile.js').read(file);
  const blanks = Object.entries(vars)
    .filter(([, v]) => !v.trim() || v.trim() === TODO)
    .map(([k]) => k);

  /* config.js is the authority on what a production boot actually needs */
  const cfgPath = path.join(ROOT, 'server', 'config.js');
  const required = [...fs.readFileSync(cfgPath, 'utf8')
    .matchAll(/\{ k: '([A-Z_]+)', phase: (\d+)/g)].map(m => m[1]);

  const blocking = blanks.filter(k => required.includes(k));
  const other = blanks.filter(k => !required.includes(k));

  console.log(`\n  ${file}\n`);
  if (blocking.length) {
    console.log('  the boot will refuse to start without these:');
    for (const k of blocking) console.log(`    ${k.padEnd(30)} ${FROM_ELSEWHERE[k] || ''}`);
  } else {
    console.log('  every secret the boot demands is filled in.');
  }
  if (other.length) {
    console.log('\n  …and these are still blank (the app starts without them, but');
    console.log('  replication does not):');
    for (const k of other) console.log(`    ${k.padEnd(30)} ${FROM_ELSEWHERE[k] || ''}`);
  }
  console.log('');
  return blocking.length;
}

const args = process.argv.slice(2);
if (args[0] === '--check') {
  process.exit(check(path.resolve(args[1] || path.join(ROOT, '.env'))) ? 1 : 0);
}

const out = path.resolve(args[0] || path.join(ROOT, '.env'));
if (fs.existsSync(out)) {
  console.error(`\n  ${out} already exists — not touching it.\n`);
  console.error('  Regenerating would mint a new SESSION_SECRET, which signs out every');
  console.error('  visitor on the wall and takes their history with them. Delete it by');
  console.error('  hand if that is genuinely what you want.\n');
  process.exit(1);
}

fs.writeFileSync(out, build(), { mode: 0o600 });
console.log(`\n  wrote ${out} (chmod 600)\n`);
console.log(`  ${GENERATE.join(' and ')} are generated and final.`);
console.log('  Keep a copy of SESSION_SECRET somewhere off the box — the restore');
console.log('  drill needs it, and without it every guest loses their history.\n');
check(out);
